// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPG_Character_System;

#nullable disable

namespace RPG_Character_System.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20251120095113_SecondMigr")]
    partial class SecondMigr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharacterQuest", b =>
                {
                    b.Property<int>("CharactersId")
                        .HasColumnType("int");

                    b.Property<int>("QuestsId")
                        .HasColumnType("int");

                    b.HasKey("CharactersId", "QuestsId");

                    b.HasIndex("QuestsId");

                    b.ToTable("CharacterQuests", (string)null);
                });

            modelBuilder.Entity("RPG_Character_System.Characters.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassType")
                        .HasColumnType("int");

                    b.Property<int?>("EquippedWeaponId")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EquippedWeaponId")
                        .IsUnique()
                        .HasFilter("[EquippedWeaponId] IS NOT NULL");

                    b.ToTable("Characters", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("RPG_Character_System.Characters.CharacterDto", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CharacterDTO");
                });

            modelBuilder.Entity("RPG_Character_System.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("RPG_Character_System.Systems.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Slay the dragon in the northern mountains.",
                            IsCompleted = false,
                            Title = "Defeat the Dragon"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Recover the legendary blade from ancient ruins.",
                            IsCompleted = false,
                            Title = "Find the Lost Sword"
                        });
                });

            modelBuilder.Entity("RPG_Character_System.Characters.Mage", b =>
                {
                    b.HasBaseType("RPG_Character_System.Characters.Character");

                    b.Property<int>("SpellDamage")
                        .HasColumnType("int");

                    b.ToTable("Mages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            ClassType = 1,
                            EquippedWeaponId = 2,
                            Experience = 400,
                            Health = 80,
                            Level = 6,
                            Name = "Elora",
                            SpellDamage = 100
                        });
                });

            modelBuilder.Entity("RPG_Character_System.Characters.Warrior", b =>
                {
                    b.HasBaseType("RPG_Character_System.Characters.Character");

                    b.Property<int>("BonusDamage")
                        .HasColumnType("int");

                    b.ToTable("Warriors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassType = 0,
                            EquippedWeaponId = 1,
                            Experience = 300,
                            Health = 120,
                            Level = 5,
                            Name = "Thorin",
                            BonusDamage = 110
                        });
                });

            modelBuilder.Entity("RPG_Character_System.Items.Weapon", b =>
                {
                    b.HasBaseType("RPG_Character_System.Items.Item");

                    b.Property<int>("AttackPower")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.ToTable("Weapons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Steel Sword",
                            AttackPower = 20
                        },
                        new
                        {
                            Id = 2,
                            Name = "Arcane Staff",
                            AttackPower = 25
                        });
                });

            modelBuilder.Entity("CharacterQuest", b =>
                {
                    b.HasOne("RPG_Character_System.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPG_Character_System.Systems.Quest", null)
                        .WithMany()
                        .HasForeignKey("QuestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RPG_Character_System.Characters.Character", b =>
                {
                    b.HasOne("RPG_Character_System.Items.Weapon", "EquippedWeapon")
                        .WithOne("Character")
                        .HasForeignKey("RPG_Character_System.Characters.Character", "EquippedWeaponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquippedWeapon");
                });

            modelBuilder.Entity("RPG_Character_System.Characters.Mage", b =>
                {
                    b.HasOne("RPG_Character_System.Characters.Character", null)
                        .WithOne()
                        .HasForeignKey("RPG_Character_System.Characters.Mage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RPG_Character_System.Characters.Warrior", b =>
                {
                    b.HasOne("RPG_Character_System.Characters.Character", null)
                        .WithOne()
                        .HasForeignKey("RPG_Character_System.Characters.Warrior", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RPG_Character_System.Items.Weapon", b =>
                {
                    b.HasOne("RPG_Character_System.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("RPG_Character_System.Items.Weapon", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RPG_Character_System.Items.Weapon", b =>
                {
                    b.Navigation("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
